### ISSUE TITLE
PyTorch Geometric implementation

### ISSUE THREAD

**Issue by dtchang** [devalab/CIGIN#2]
If not too much trouble, please adapt the code to use PyTorch Geometric. This has two benefits: (1) MessagePassing will conform to the common usage as a base class (framework) to be subclassed / implemented with concrete message, aggregation and update functions, and (2) All types of graph convolutions that subclass from MessagePassing in PyTorch Geometric can readily be used for the message passing phase.

Thanks.

**Comment by yp201** [comment]
Hi,
Thanks for your inputs, we would update the code with deep graph library. (https://www.dgl.ai/) shortly, in our second version,both are similar libraries. 
You may look this up for performance comparisons. https://github.com/dmlc/dgl
