### ISSUE TITLE
CIGIN_V2

### ISSUE THREAD

**Issue by dtchang** [devalab/CIGIN#4]
The code has issues. Here are trivial examples:
(1) main.py: dgl is undefined
(2) model.py: np is undefined

Please make necessary corrections, ensure the code runs, and ensure it generates expected results. Thanks.

**Comment by yp201** [comment]
Hi, Chang.
The code runs expected. 1) and 2) were being imported in the corresponding helper files, but for ease of use, we have fixed it.
Thanks
