### ISSUE TITLE
Hi, Chang.

### ISSUE THREAD

**Issue by dtchang** [devalab/CIGIN#5]
Hi, Chang.
The code runs expected. 1) and 2) were being imported in the corresponding helper files, but for ease of use, we have fixed it.
Thanks

_Originally posted by @yp201 in https://github.com/devalab/CIGIN/issues/4#issuecomment-670475170_

2) is not fixed: np is undefined in model.py. (There may be more.) Please run the code as is, without external files, fix all errors and verify results.

**Comment by yp201** [comment]
done.
thanks.

**Comment by dtchang** [comment]
It runs now. Thanks.
